title: Data structures course
description: YOUR DESCRIPTION
#theme: just-the-docs
plugins:
  - jekyll-default-layout

url: https://gustavogutierrezutp.github.io/is304

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/gustavogutierrezutp/is304