title: Data structures IS304
description: YOUR DESCRIPTION
theme: just-the-docs


url: https://gustavogutierrezutp.github.io

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/gustavogutierrezutp/is304
